substitutions:
  name: esp-web-tools-example-716a9a
  friendly_name: Bedroom
packages:
  esphome.esp_web_tools_example: github://esphome/example-configs/esp-web-tools/esp8266.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: your api key

binary_sensor:
  - platform: gpio
    id: fanInput
    pin:
      number: GPIO1
      inverted: True
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.turn_on: fanSwitch
    on_release:
      then:
        - switch.turn_off: fanSwitch

  - platform: gpio
    id: lightInput
    pin:
      number: GPIO3
      inverted: True
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.turn_on: lightSwitch
    on_release:
      then:
        - switch.turn_off: lightSwitch

  - platform: gpio
    id: nightLampInput
    pin:
      number: GPIO15
      inverted: True
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.turn_on: nightLampSwitch
    on_release:
      then:
        - switch.turn_off: nightLampSwitch

  - platform: gpio
    pin:
      number: GPIO5
      mode:
        input: True
    name: "Motion"
    device_class: motion

  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    name: "Rain"

switch:
  - platform: gpio
    name: "Fan"
    pin: GPIO12
    id: fanSwitch
    inverted: True

  - platform: gpio
    name: "Light"
    pin: GPIO14
    id: lightSwitch
    inverted: True

  - platform: gpio
    name: "Night Lamp"
    pin: GPIO13
    id: nightLampSwitch
    inverted: True

sensor:
  - platform: dht
    pin:
      number: GPIO16
      mode:
        input: True
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 5s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.101
    gateway: 192.168.1.1
    subnet: 255.255.255.0
