substitutions:
  name: esp-web-tools-example-de04c7
  friendly_name: Drawing Room
packages:
  esphome.esp_web_tools_example: github://esphome/example-configs/esp-web-tools/esp8266.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: your api key

text_sensor:
  - platform: homeassistant
    entity_id: input_text.message_board
    name: "Message Board"
    id: message_board

i2c:
  sda: GPIO13
  scl: GPIO12

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    lambda: |-
      it.printf(id(message_board).state.c_str());

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.103
    gateway: 192.168.1.1
    subnet: 255.255.255.0
