substitutions:
  name: esp-web-tools-example-de04c7
  friendly_name: Drawing Room
packages:
  esphome.esp_web_tools_example: github://esphome/example-configs/esp-web-tools/esp8266.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: your api key

text_sensor:
  - platform: homeassistant
    entity_id: input_text.message_board
    name: "Message Board"
    id: message_board

i2c:
  sda: GPIO13
  scl: GPIO12

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    lambda: |-
      it.printf(id(message_board).state.c_str());


one_wire:
  - platform: gpio
    pin: GPIO4

sensor:
  - platform: dallas_temp
    accuracy_decimals: 2
    name: temperature
    update_interval: 5s 

servo:
  - id: my_servo
    output: pwm_output

number:
  - platform: template
    name: Servo Control
    min_value: -100
    initial_value: 0
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: my_servo
            level: !lambda 'return x / 100.0;'

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: GPIO5
    frequency: 50 Hz
  
  - platform: esp8266_pwm
    id: red
    pin: 
      number: GPIO3

  - platform: esp8266_pwm
    id: green
    pin: 
      number: GPIO1

  - platform: esp8266_pwm
    id: blue
    pin: 
      number: GPIO14

light:
  - platform: rgb
    name: "RGB Light"
    blue: blue
    red: red
    green: green

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.103
    gateway: 192.168.1.1
    subnet: 255.255.255.0
