substitutions:
  name: esp-web-tools-example-716a9a
  friendly_name: Outdoor's ESP8266
packages:
  esphome.esp_web_tools_example: github://esphome/example-configs/esp-web-tools/esp8266.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: API Key

binary_sensor:
  - platform: gpio
    id: waterPump
    pin:
      number: GPIO13
      inverted: True
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.turn_on: waterPumpSwitch
    on_release:
      then:
        - switch.turn_off: waterPumpSwitch

  - platform: gpio
    id: outdoorsLight
    pin:
      number: GPIO12
      inverted: True
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.turn_on: outdoorsLightSwitch
    on_release:
      then:
        - switch.turn_off: outdoorsLightSwitch

  - platform: gpio
    pin:
      number: GPIO14
      inverted: True
    name: "Main Gate"
    device_class: door

  - platform: gpio
    pin:
      number: GPIO5
      mode:
        input: True
    name: "Outdoor Motion"
    device_class: motion

  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    name: "Outdoor Rain"

switch:
  - platform: gpio
    name: "Water Pump"
    pin: GPIO3
    id: waterPumpSwitch
    inverted: True

  - platform: gpio
    name: "Light"
    pin: GPIO1
    id: outdoorsLightSwitch
    inverted: True

  - platform: gpio
    name: "Buzzer"
    pin: GPIO0

sensor:
  - platform: dht
    pin:
      number: GPIO16
      mode:
        input: True
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 2s

wifi:
  ssid: abc
  password: abc
  manual_ip:
    static_ip: 192.168.31.216
    gateway: 192.168.31.1
    subnet: 255.255.255.0
