substitutions:
  name: esp-web-tools-example-de1426
  friendly_name: Outdoor
packages:
  esphome.esp_web_tools_example: github://esphome/example-configs/esp-web-tools/esp8266.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: your api key

binary_sensor:
  - platform: gpio
    id: waterPumpInput
    pin:
      number: GPIO5
      inverted: True
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.turn_on: waterPumpSwitch
    on_release:
      then:
        - switch.turn_off: waterPumpSwitch

  - platform: gpio
    id: lightInput
    pin:
      number: GPIO12
      inverted: True
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.turn_on: lightSwitch
    on_release:
      then:
        - switch.turn_off: lightSwitch

switch:
  - platform: gpio
    name: "Water Pump"
    pin: GPIO3
    id: waterPumpSwitch
    inverted: True

  - platform: gpio
    name: "Light"
    pin: GPIO1
    id: lightSwitch
    inverted: True

light:
  - platform: rgb
    name: "RGB Light"
    red: red
    green: green
    blue: blue

output:
  - platform: esp8266_pwm
    id: red
    pin:
      number: GPIO13

  - platform: esp8266_pwm
    id: green
    pin:
      number: GPIO0

  - platform: esp8266_pwm
    id: blue
    pin:
      number: GPIO2

sensor:
  - platform: ultrasonic
    trigger_pin: GPIO14
    echo_pin: GPIO4
    name: "Water Tank Empty Level"
    update_interval: 5s

wifi:
  #  ssid: !secret wifi_ssid
  #  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.102
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap: {}
